name: test_auto_tags

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  jobs_v:
    name: 构建版本号和变更信息
    runs-on: ubuntu-latest
    outputs:
      NewVersion: ${{ steps.create_version.outputs.NewVersion }} 
      Body: ${{ steps.create_body.outputs.Body }} 
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: 检查是否 "发布"
        run: |
          echo "New Body: ${{ steps.jobs_v.outputs.newBody }}"
          
          latest_commit_message=$(git log -1 --pretty=%B)
          if [[ $latest_commit_message == *"发布"* ]]; then
            echo "找到发布关键字继续工作流"
          else
            echo "没有找到发布关键字停止工作流"
            exit 1  # 停止工作流程
          fi
      - name: 递增版本号
        id: create_version
        uses: duolabmeng6/action-autotag-python@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 查看版本号
        run: |
          echo ${{ format('version={0}', steps.create_version.outputs.NewVersion ) }}

      - name: 从提交记录中获取更新日志
        id: create_body
        uses: duolabmeng6/action-Releases-log@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 查看提交记录
        run: |
          git log --pretty=format:"%an|%s|%h|%ad|%H" --date=format:"%Y-%m-%d %H:%M" $(git describe --tags --abbrev=0)^..HEAD
      - name: Set the value in bash
        id: step_one
        run: |
          {
            echo 'JSON_RESPONSE<<EOF'
              # GoEasyDesigner 窗口设计师

              奋斗了1小时，本次更新内容如下：

              哈哈哈[多啦b梦 13b10d2](https://github.com/duolabmeng6/learn_actions/commit/13b10d28fee34f5dfb370d5b4b0778f26f59889f) 2023-11-04 19:31
            echo EOF
          } >> "$GITHUB_ENV"

      - name: 查看更新日志
        run: |
          echo ${{ steps.create_body.outputs.Body }}





