name: 发布软件

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all


jobs:
  jobs1:
    name : 构建版本号和变更信息
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create_version.outputs.tag_name }}
      body: ${{ steps.create_version.outputs.body }}
    steps:
      # 写出版本号以及变化记录
      - uses: release-drafter/release-drafter@v5
        id: create_version
        # 配置文件在 .github/release-drafter.yml
        with:
          config-name: release-drafter.yml # 配置文件
          prerelease: false # 禁止发布 防止重复发布2次
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 定义输出变量 # 查看发布的版本
        run: |
          echo ${{ format('version={0}', steps.create_version.outputs.tag_name ) }}

  jobs2:
    needs: jobs1
    name: 构建window软件
    runs-on: ubuntu-latest
    env:
      version: ${{ needs.jobs1.outputs.version }}
      body: ${{ needs.jobs1.outputs.body }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 读入环境信息
        run: |
          echo ${{ format('version {0}', env.version ) }}
      - name: 编译
          mkdir down
          echo "123456789" >> ./down/QtEasyDesigner.exe
          ls -al
      - name: 上传资产
          echo "上传资产"


  jobs3:
    needs: jobs2
    name: 构建macos软件
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 读入环境信息
        run: |
          mkdir down
          echo "123456789" >> ./down/QtEasyDesigner_MacOS.zip
          ls -al
      - name: 上传资产
          echo "上传资产"