name: 学习

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  task1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 检查目录文件
        run: ls -al
      - name: 写出文件
        run:  |
          echo "Hello World" >> hello.txt
          ls -al
      - name: 读入文件
        run:  |
          文本内容=$(cat hello.txt)
          echo $文本内容
      - name: 下载依赖文件
        run: echo 正在下载依赖文件
      - name: 构建软件
        run: |
          echo 构建软件
          echo 构建完成
      - name: 测试软件
        run: |
          echo 测试软件
          echo 123456789
          echo 测试通过
      - name: 检查上一步的输出
        run: |
          echo 不知道咋写等一下查

  task2:
    needs: task1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 下载构建产物
        run: echo 下载构建产物
      - name: 发布文件
        run: |
          echo 发布文件
          echo 发布完成
