name: 学习

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SERVER: production
  应用名称: 学习1.0
  
  
jobs:
  task1:
    name: 任务1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 检查目录文件
        run: ls -al
      - name: 安装Python
        uses: actions/setup-python@v4.1.0
        with:
          cache: pip
      - name: 检查python版本
        run: |
          python -V
          pip -V
