name: 学习

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SERVER: production
  myval: myval
  应用名称: 学习1.0
  
  
jobs:
  task1:
    name: 任务1
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      output3: ${{ steps.step3.outputs.test }}
      output4: ${{ steps.step3.outputs.test2 }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 检查目录文件
        run: ls -al
      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: 安装依赖文件
        run: |
          pip install -r requirements.txt
      - name: 检查python版本
        run: |
          python -V
          pip -V
      - name: 运行 python 脚本 run_success.py
        id: step_run_success
        run: |
          python run_success.py

      - name: 运行 python 脚本
        id: step3
        run: |

          echo ${{ format('读取环境变量myval {0}', env.myval) }}
          python actions_读入环境变量和写出环境变量.py
      - name: 运行 python 脚本 第二个
        run: |
          python actions_读入环境变量和写出环境变量.py
      - name: 读取环境变量
        run: |
          echo ${{ format('读取环境变量aaa {0}', env.aaa) }}
          echo ${{ format('读取环境变量bbb {0}', env.bbb) }}
          echo ${{ format('读取环境变量myval {0}', env.myval) }}

      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"

  task2:
    needs: task1
    name: 任务2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 检查目录文件
        run: ls -al
      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: 安装依赖文件
        run: |
          pip install -r requirements.txt
      - name: 读取环境变量
        run: |
          echo ${{ format('读取环境变量aaa {0}', env.aaa) }}
          echo ${{ format('读取环境变量bbb {0}', env.bbb) }}
      - name: 运行 python 脚本
        run: |
          python actions_读入环境变量和写出环境变量.py
      - name: 读取task1的输出
        run: |
          echo ${{ format('output1 {0}', needs.task1.outputs.output1) }}
          echo ${{ format('output2 {0}', needs.task1.outputs.output2) }}
          echo ${{ format('output3 {0}', needs.task1.outputs.output3) }}
          echo ${{ format('output4 {0}', needs.task1.outputs.output4) }}