name: 学习

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SERVER: production
  myval: myval
  应用名称: 学习1.0
  
  
jobs:
  task1:
    name: 任务1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 检查目录文件
        run: ls -al
      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: 安装依赖文件
        run: |
          pip install -r requirements.txt
      - name: 运行 python 写出文件
        run: |
          python actions_写出文件.py
      - name: 上传工程文件
        uses: actions/upload-artifact@v3
        with:
          name: myfile
          path: content.txt # 上传目录 path/to/artifact/

  task2:
    needs: task1
    name: 任务2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 检查目录文件
        run: ls -al
      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: 安装依赖文件
        run: |
          pip install -r requirements.txt
      - name: 下载工程文件
        uses: actions/download-artifact@v3
        id: download
        with:
          name: myfile
          path: ./down/ # 下载目录
      - name: 读取文件内容
        run: |
          cd ${{steps.download.outputs.download-path}}
          ls -al
          echo ${{steps.download.outputs.download-path}}
          cat content.txt