name: 学习

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SERVER: production
  应用名称: 学习1.0
  
  
jobs:
  task1:
    name: 任务1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 检查目录文件
        run: ls -al
      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - name: 安装依赖文件
        run: |
          pip install -r requirements.txt
      - name: 检查python版本
        run: |
          python -V
          pip -V
      - name: 运行 python 脚本
        run: |
          python actions_读入环境变量和写出环境变量.py
