name: 版本信息发布

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

  workflow_dispatch:

permissions: write-all

jobs:
  name : 信息发布
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # 写出版本号以及变化记录
      - uses: release-drafter/release-drafter@v5
        id: create_release
        # 配置文件在 .github/release-drafter.yml
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: echo
        run: echo "::set-output name=tag_name::" + ${{ steps.create_release.outputs.tag_name }}

  release:
    name : 发布资产 
    needs: update_release_draft
      - name: 构建软件
        run: |
          mkdir down
          echo "123456789" >> ./down/QtEasyDesigner.exe
          echo "123456789" >> ./down/QtEasyDesigner_MacOS.zip
          ls -al
      - name: 发布资产文件
        uses: softprops/action-gh-release@v1
        with:
          draft: true # 草稿别人看不见 需要手动发布1
          generate_release_notes: false
          tag_name: ${{ needs.update_release_draft.steps.create_release.outputs.tag_name }} # v0.1.1
          files: ./down/*
