name: 版本信息发布

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write 
    runs-on: ubuntu-latest
    steps:
      # 写出版本号以及变化记录
      - uses: release-drafter/release-drafter@v5
        id: create_release
        # 配置文件在 .github/release-drafter.yml
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 运行 python 写出文件
        run: |
          echo "123456789" >> content.txt

      - name: 发布资产文件
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          files: content.txt
