name: 版本信息发布

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

  workflow_dispatch:

permissions: write-all

jobs:
  update_release_draft:
    name : 信息发布
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_release.outputs.tag_name }}
    steps:
      # 写出版本号以及变化记录
      - uses: release-drafter/release-drafter@v5
        id: create_release
        # 配置文件在 .github/release-drafter.yml
        with:
          config-name: release-drafter.yml # 配置文件
          prerelease: false # 禁止发布 防止重复发布2次
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 输出变量 # 查看发布的版本
        run: |
          echo ${{ format('tag_name {0}', steps.create_release.outputs.tag_name ) }} 
      - name: 构建软件
        run: |
          mkdir down
          echo "123456789" >> ./down/QtEasyDesigner.exe
          echo "123456789" >> ./down/QtEasyDesigner_MacOS.zip
          ls -al
      - name: 发布资产文件 # 发布文件
        uses: ncipollo/release-action@v1 # 发布版本 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true # 覆盖文件 
          #draft: true # 草稿 自己可见 默认 自动发布新版本
          tag: ${{ steps.create_release.outputs.tag_name }} # 版本号 v0.1.0
          body: ${{ steps.create_release.outputs.body }} # 输出的内容
          artifacts: "./down/*"
