name: 版本信息发布

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write 
    runs-on: ubuntu-latest
    steps:
      # 写出版本号以及变化记录
      - uses: release-drafter/release-drafter@v5
        id: create_release
        # 配置文件在 .github/release-drafter.yml
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建软件
        run: |
          mkdir down
          echo "123456789" >> ./down/QtEasyDesigner.exe
          echo "123456789" >> ./down/QtEasyDesigner_MacOS.zip
          ls -al

      - name: 发布资产文件
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ steps.create_release.outputs.name }}
          files: ./down/*
