name: 版本信息发布

on:
  pull_request:
  workflow_dispatch:

permissions: write-all
jobs:
  auto-merge:
    - name: Merge
      uses: KeisukeYamashita/auto-pull-request-merge@v1
      with:
        intervalSeconds: 10
        timeoutSeconds: 30