name: 自动合并请求

on:
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:
  update_release_draft:
    name : 自动合并请求
    runs-on: ubuntu-latest
    steps:
      - name: 自动合并请求 # 发布文件
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          intervalSeconds: 10
          timeoutSeconds: 30
