name: 钉钉通知测试

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

permissions: write-all


jobs:
  jobs_v:
    name : 构建版本号和变更信息
    runs-on: ubuntu-latest
    steps:
    - name: 定义发送消息的内容
      run: |

    - name: 发送钉钉通知
      uses: zcong1993/actions-ding@master
      with:
        dingToken: ${{ secrets.DING_TOKEN }}
        secret: ${{ secrets.DING_SECRET }} 
        body: |
          {
            "msgtype": "link",
            "link": {
                "text": "请前往查看",
                "title": "QtEasyDesigner v0.0.1 版本已发布 ${{ env.GITHUB_ACTION_REPOSITORY }}",
                "messageUrl": "https://github.co/${{ env.GITHUB_ACTION_REPOSITORY }}/releases"
            }
          }